# Generated by Django 5.2.6 on 2026-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_backfill_restaurants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="image_url",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
    ]
